DEFAULT_THRESHOLDS = {
    'SYN_THRESHOLD': 50,
    'DST_THRESHOLD': 20,
    'ICMP_THRESHOLD': 80,
    'ARP_THRESHOLD': 80,
    'PPS_THRESHOLD': 500,              
    'BPS_THRESHOLD': 1000000,
    'DOS_PACKET_THRESHOLD': 1000,
    'DOS_TIME_WINDOW': 10,             
}
